"""added direction models and some fixes in column

Revision ID: 66c940b91d74
Revises: 4aa0dd9e6402
Create Date: 2024-08-28 05:03:41.750877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66c940b91d74'
down_revision = '4aa0dd9e6402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('step_number', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('quantity')

    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('oven_temp', sa.Integer(), nullable=True))
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('oven_temp')

    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.VARCHAR(length=50), autoincrement=False, nullable=False))

    op.drop_table('instruction')
    # ### end Alembic commands ###
